export const MOSTRAR_CITAS = 'MOSTRAR_CITAS';
export const AGREGAR_CITA = 'AGREGAR_CITAS';
export const BORRAR_CITA = 'BORRAR_CITA';

export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO'
export const MOSTRAR_ERROR = 'MOSTRAR_ERROR'

